export default {
    THEME_CHANGE: Symbol('THEME_CHANGE'),
    THEME_INIT: Symbol('THEME_INIT'),
    POPULAR_REFRESH: Symbol('POPULAR_REFRESH'),
    POPULAR_lOAD_FAIL:Symbol('POPULAR_lOAD_FAIL'),
    POPULAR_lOAD_SUCCESS:Symbol('POPULAR_lOAD_SUCCESS')
};